/**
 * Document Management Page
 * Main page for viewing and managing documents with action tracking
 */
import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { documentsService } from '../services/documents.service';
import { EnrichedDocument, DocumentListResponse } from '../types';
import { AlertCircle, FileText, Flag, CheckCircle, XCircle, Clock, ArrowLeft, Share2, Download, Mail } from 'lucide-react';
import DocumentFilters from '../components/documents/DocumentFilters';
import ExpandableDocumentCard from '../components/documents/ExpandableDocumentCard';

const DocumentManagementPage: React.FC = () => {
  const navigate = useNavigate();
  const [documents, setDocuments] = useState<EnrichedDocument[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [stats, setStats] = useState({
    total: 0,
    flagged: 0,
    pending: 0,
    followup: 0,
    resolved: 0
  });
  const [showShareMenu, setShowShareMenu] = useState(false);
  const shareMenuRef = useRef<HTMLDivElement>(null);

  // Filter state
  const [profileFilter, setProfileFilter] = useState<string>('all');
  const [actionFilter, setActionFilter] = useState<string>('all');
  const [flaggedOnly, setFlaggedOnly] = useState(false);

  // Load documents
  const loadDocuments = async () => {
    try {
      setLoading(true);
      setError(null);

      const params = {
        profile_id: profileFilter !== 'all' ? profileFilter : undefined,
        action: actionFilter !== 'all' ? actionFilter : undefined,
        flagged_only: flaggedOnly
      };

      const response: DocumentListResponse = await documentsService.listDocumentsEnhanced(params);
      setDocuments(response.documents);

      // Calculate stats
      const newStats = {
        total: response.total,
        flagged: response.documents.filter(d => d.flagged).length,
        pending: response.documents.filter(d => !d.action && d.status === 'uploaded').length,
        followup: response.documents.filter(d => d.action === 'followup').length,
        resolved: response.documents.filter(d => d.action === 'resolved').length
      };
      setStats(newStats);

    } catch (err) {
      console.error('❌ Failed to load documents:', err);
      setError(err instanceof Error ? err.message : 'Failed to load documents');
    } finally {
      setLoading(false);
    }
  };

  // Load documents on mount and when filters change
  useEffect(() => {
    loadDocuments();
  }, [profileFilter, actionFilter, flaggedOnly]);

  // Close share menu when clicking outside
  useEffect(() => {
    if (!showShareMenu) return;
    const handler = (e: MouseEvent) => {
      if (shareMenuRef.current && !shareMenuRef.current.contains(e.target as Node)) {
        setShowShareMenu(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [showShareMenu]);

  const generateReport = () => {
    const lines: string[] = [
      'DOCUMENT MANAGEMENT REPORT',
      `Generated: ${new Date().toLocaleString()}`,
      '='.repeat(60),
      '',
      'SUMMARY',
      `Total Documents: ${stats.total}`,
      `Flagged:         ${stats.flagged}`,
      `Pending:         ${stats.pending}`,
      `Follow-up:       ${stats.followup}`,
      `Resolved:        ${stats.resolved}`,
      '',
      '='.repeat(60),
      'DOCUMENTS',
      '='.repeat(60),
      '',
    ];
    documents.forEach((doc, i) => {
      lines.push(`${i + 1}. ${doc.filename}`);
      if (doc.document_type) lines.push(`   Type:     ${doc.document_type.replace(/_/g, ' ')}`);
      if (doc.profile_name)  lines.push(`   Profile:  ${doc.profile_name}`);
      lines.push(`   Status:   ${doc.flagged ? 'FLAGGED' : doc.action ?? 'pending'}`);
      if (doc.total_issues_count > 0)
        lines.push(`   Issues:   ${doc.total_issues_count} (${doc.high_confidence_issues_count} high-confidence)`);
      if (doc.action_notes)  lines.push(`   Notes:    ${doc.action_notes}`);
      lines.push('');
    });
    lines.push('='.repeat(60));
    lines.push('Generated by MedBillDozer — AI-Powered Medical Billing Analysis');
    lines.push('https://medbilldozer.com');
    return lines.join('\n');
  };

  const handleDownload = () => {
    const text = generateReport();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medbilldozer-documents-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setShowShareMenu(false);
  };

  const handleEmailShare = () => {
    const subject = encodeURIComponent(
      `MedBillDozer: ${stats.total} document(s), ${stats.flagged} flagged`
    );
    const body = encodeURIComponent(generateReport());
    window.open(`mailto:?subject=${subject}&body=${body}`);
    setShowShareMenu(false);
  };

  const handleNativeShare = async () => {
    try {
      await navigator.share({ title: 'MedBillDozer Document Report', text: generateReport() });
    } catch {
      // user cancelled or API unavailable
    }
    setShowShareMenu(false);
  };

  // Handle document action update
  const handleDocumentUpdate = async () => {
    // Reload documents to reflect changes
    await loadDocuments();
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-4 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            Back to Home
          </button>
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-2">
                <FileText className="w-8 h-8 text-blue-600" />
                Document Management
              </h1>
              <p className="mt-2 text-gray-600">
                View, track, and manage your medical documents with action status
              </p>
            </div>

            {!loading && documents.length > 0 && (
              <div className="relative mt-1" ref={shareMenuRef}>
                <button
                  onClick={() => setShowShareMenu(prev => !prev)}
                  className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-sm font-medium text-gray-700 shadow-sm transition-colors"
                >
                  <Share2 size={16} />
                  Share / Export
                </button>

                {showShareMenu && (
                  <div className="absolute right-0 mt-2 w-52 bg-white rounded-xl shadow-lg border border-gray-200 py-1.5 z-20">
                    <button
                      onClick={handleDownload}
                      className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      <Download size={15} className="text-gray-500 flex-shrink-0" />
                      Download report (.txt)
                    </button>
                    <button
                      onClick={handleEmailShare}
                      className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      <Mail size={15} className="text-gray-500 flex-shrink-0" />
                      Send via Email
                    </button>
                    {typeof navigator !== 'undefined' && !!navigator.share && (
                      <button
                        onClick={handleNativeShare}
                        className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                      >
                        <Share2 size={15} className="text-gray-500 flex-shrink-0" />
                        Share…
                      </button>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Statistics Cards */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4 mb-8">
          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Documents</p>
                <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
              </div>
              <FileText className="w-8 h-8 text-gray-400" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Flagged</p>
                <p className="text-2xl font-bold text-red-600">{stats.flagged}</p>
              </div>
              <Flag className="w-8 h-8 text-red-400" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Pending</p>
                <p className="text-2xl font-bold text-gray-600">{stats.pending}</p>
              </div>
              <Clock className="w-8 h-8 text-gray-400" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Follow-up</p>
                <p className="text-2xl font-bold text-yellow-600">{stats.followup}</p>
              </div>
              <AlertCircle className="w-8 h-8 text-yellow-400" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Resolved</p>
                <p className="text-2xl font-bold text-green-600">{stats.resolved}</p>
              </div>
              <CheckCircle className="w-8 h-8 text-green-400" />
            </div>
          </div>
        </div>

        {/* Filters */}
        <DocumentFilters
          profileFilter={profileFilter}
          setProfileFilter={setProfileFilter}
          actionFilter={actionFilter}
          setActionFilter={setActionFilter}
          flaggedOnly={flaggedOnly}
          setFlaggedOnly={setFlaggedOnly}
        />

        {/* Document List */}
        <div className="mt-8">
          {loading && (
            <div className="text-center py-12">
              <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
              <p className="mt-4 text-gray-600">Loading documents...</p>
            </div>
          )}

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 flex items-start gap-3">
              <XCircle className="w-5 h-5 text-red-600 mt-0.5" />
              <div>
                <p className="font-medium text-red-900">Error loading documents</p>
                <p className="text-sm text-red-700 mt-1">{error}</p>
              </div>
            </div>
          )}

          {!loading && !error && documents.length === 0 && (
            <div className="text-center py-12 bg-white rounded-lg shadow">
              <FileText className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <p className="text-gray-600 text-lg">No documents found</p>
              <p className="text-gray-500 text-sm mt-2">Try adjusting your filters or upload new documents</p>
            </div>
          )}

          {!loading && !error && documents.length > 0 && (
            <div className="space-y-4">
              {documents.map((document) => (
                <ExpandableDocumentCard
                  key={document.document_id}
                  document={document}
                  onUpdate={handleDocumentUpdate}
                />
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DocumentManagementPage;
